### ISSUE TITLE
go build does not work

### ISSUE THREAD

**Issue by firstrow** [felixangell/phi-editor#25]
```
# github.com/felixangell/phi-editor/gui
gui/buffer.go:669:8: undefined: strife.MouseWheelEvent
gui/buffer.go:670:11: event.Y undefined (type strife.StrifeEvent has no field or method Y)
gui/buffer.go:673:11: event.Y undefined (type strife.StrifeEvent has no field or method Y)
```

**Comment by felixangell** [comment]
Ah my bad, I made some changes to the graphics library. If you try again it should work now @firstrow

**Comment by firstrow** [comment]
Thanks. It also would be nice to have vendoring support.

**Comment by firstrow** [comment]
```
phi-editor - master ❯ go get -u github.com/felixangell/phi-editor
# github.com/felixangell/phi-editor/gui                    
gui/buffer.go:85:6: undefined: f                           
gui/buffer.go:88:4: undefined: f
```

**Comment by felixangell** [comment]
@firstrow Ah that's a bug from the PR, just fixed it. You might have to merge with master though again

**Comment by felixangell** [comment]
w/r/t vendor I'll look into that, I've never used it before. I presume you mean use that with the strife repository? 
Maybe if the editor has a stable release, but I like the fact that everything is using the latest repo so everything kind of has to work type thing.

**Comment by firstrow** [comment]
You know what is weird? Yesterday I was thinking about text editor using GPU to render all the things. And today I've found your lib in go trending. Recently I've found atom/xray, but I do not like the idea of using electron(js/css) for building fast gui applications.

**Comment by felixangell** [comment]
@firstrow hehe, that's a cool coincidence. if i'm honest the only reason I made it is because I love the block cursors and no editors I like (mostly sublime) seem to have them natively supported.

**Comment by firstrow** [comment]
emacs has block cursors.

**Comment by felixangell** [comment]
@firstrow ah yeah that was my goto but I'm not keen on the mac layout personally. and also i can never get the tabs configured correctly - which is another reason I wrote this editor 😄

**Comment by felixangell** [comment]
@firstrow have you managed to get this to build? can i close the issue?

**Comment by firstrow** [comment]
thanks. I got it up and running!

**Comment by felixangell** [comment]
@firstrow Great! thanks for reporting this :)
